### ISSUE TITLE
[TODO] class attributes

### ISSUE THREAD

**Issue by dixyes** [toastrun/docs.toast.run#2]
- [ ] parse class implement extends
- [ ] parse class use
- [ ] make structured data
- [ ] make highlight
