### ISSUE TITLE
[TODO] 丰富内容 Add contents

### ISSUE THREAD

**Issue by dixyes** [toastrun/docs.toast.run#5]
- [ ] 添加示例 Add examples
- [ ] 添加手写的常见用法指引 Add usage guides wrote by hand
- [ ] 添加常见坑 Add common pits
- [ ] 搬运FAQ Copy FAQ here: https://github.com/swow/swow/discussions/116
