### ISSUE TITLE
[TODO] workflows

### ISSUE THREAD

**Issue by dixyes** [toastrun/docs.toast.run#6]
- [x] add workflows for automatic generate docs
- [ ] add workflows to sync from swow
- [ ] add workflows to sync from libcat
- [x] add workflows to update docs.toast.run
